// Mock category data with subcategories for mega menu
export const mockCategories = [
  {
    id: "shop",
    label: "Shop",
    url: "/products",
    enabled: true,
    order: 1,
    children: [
      {
        id: "women",
        label: "Women",
        url: "/products?category=women",
        enabled: true,
        order: 1,
        children: [
          { id: "women-dresses", label: "Dresses", url: "/products?category=women-dresses", enabled: true, order: 1 },
          { id: "women-tops", label: "Tops & Blouses", url: "/products?category=women-tops", enabled: true, order: 2 },
          { id: "women-pants", label: "Pants & Jeans", url: "/products?category=women-pants", enabled: true, order: 3 },
          { id: "women-skirts", label: "Skirts", url: "/products?category=women-skirts", enabled: true, order: 4 },
          {
            id: "women-outerwear",
            label: "Jackets & Coats",
            url: "/products?category=women-outerwear",
            enabled: true,
            order: 5,
          },
        ],
      },
      {
        id: "men",
        label: "Men",
        url: "/products?category=men",
        enabled: true,
        order: 2,
        children: [
          { id: "men-shirts", label: "Shirts", url: "/products?category=men-shirts", enabled: true, order: 1 },
          { id: "men-pants", label: "Pants & Jeans", url: "/products?category=men-pants", enabled: true, order: 2 },
          { id: "men-tshirts", label: "T-Shirts", url: "/products?category=men-tshirts", enabled: true, order: 3 },
          { id: "men-suits", label: "Suits & Blazers", url: "/products?category=men-suits", enabled: true, order: 4 },
          {
            id: "men-outerwear",
            label: "Jackets & Coats",
            url: "/products?category=men-outerwear",
            enabled: true,
            order: 5,
          },
        ],
      },
      {
        id: "accessories",
        label: "Accessories",
        url: "/products?category=accessories",
        enabled: true,
        order: 3,
        children: [
          { id: "bags", label: "Bags & Handbags", url: "/products?category=bags", enabled: true, order: 1 },
          { id: "jewelry", label: "Jewelry", url: "/products?category=jewelry", enabled: true, order: 2 },
          { id: "watches", label: "Watches", url: "/products?category=watches", enabled: true, order: 3 },
          { id: "belts", label: "Belts", url: "/products?category=belts", enabled: true, order: 4 },
          { id: "sunglasses", label: "Sunglasses", url: "/products?category=sunglasses", enabled: true, order: 5 },
        ],
      },
      {
        id: "shoes",
        label: "Shoes",
        url: "/products?category=shoes",
        enabled: true,
        order: 4,
        children: [
          { id: "sneakers", label: "Sneakers", url: "/products?category=sneakers", enabled: true, order: 1 },
          { id: "boots", label: "Boots", url: "/products?category=boots", enabled: true, order: 2 },
          { id: "heels", label: "Heels", url: "/products?category=heels", enabled: true, order: 3 },
          { id: "sandals", label: "Sandals", url: "/products?category=sandals", enabled: true, order: 4 },
          { id: "formal", label: "Formal Shoes", url: "/products?category=formal-shoes", enabled: true, order: 5 },
        ],
      },
    ],
  },
  {
    id: "sale",
    label: "Sale",
    url: "/products?filter=sale",
    enabled: true,
    order: 2,
  },
  {
    id: "new",
    label: "New Arrivals",
    url: "/products?filter=new",
    enabled: true,
    order: 3,
  },
  {
    id: "brands",
    label: "Brands",
    url: "/brands",
    enabled: true,
    order: 4,
  },
]
